#The Nautilus DevOps team discussed how they can train different team members to use Ansible for different automation tasks.
#There are numerous ways to perform a particular task using Ansible, but we want to utilize each aspect Ansible offers.
#to the team wants to utilise Ansible's conditionals to perform the following task:

#An inventory file is already placed under /home/thor/ansible on jump host, 
#with all the Stratos DC app servers included.

#Create a playbook /home/thor/ansible/playbook.yml and make sure to use Ansible's when 
#conditionals statements to perform the following tasks.

#Copy blog.txt file present under /usr/src/security directory on jump host to App Server 1 under 
#/opt/security directory. Its user and group owner must be user tony and its permissions must be 0744 .

#Copy story.txt file present under /usr/src/security directory on jump host to App Server 2 under 
#/opt/security directory. Its user and group owner must be user steve and its permissions must be 0744 .

#Copy media.txt file present under /usr/src/security directory on jump host to App Server 3 under 
#/opt/security directory. Its user and group owner must be user banner and its permissions must be 0744 .

#NOTE: You can use ansible_nodename variable from gathered facts with when condition. Additionally, 
#please make sure you are running the play for all hosts i.e use - hosts: all.

#Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml, 
#so please make sure playbook works this way, without passing any extra arguments.


- name: Copy file with owner and permissions
  hosts: all
  become: yes
  tasks:
  - name: "stapp01"
    copy:
        src: /usr/src/security/blog.txt
        dest: /opt/security/blog.txt
        owner: "tony"
        group: "tony"
        mode: '0744'
    when:  inventory_hostname == "stapp01"

  - name: "stapp02"
    copy:
      src: /usr/src/security/story.txt
      dest: /opt/security/story.txt
      owner: "steve"
      group: "steve"
      mode: '0744'
    when:   inventory_hostname == "stapp02"

  - name: "stapp03"
    copy:
      src: /usr/src/security/media.txt
      dest: /opt/security/media.txt
      owner: "banner"
      group: "banner"
      mode: '0744'
    when: inventory_hostname == "stapp03"